diaspora_owncloud/config/routes.rb
Rails.application.routes.draw do
  
  resources :diaspora_owncloud_status_messages, :only => [:new, :create]
  
  # Streams
  get "activity" => "diaspora_owncloud_streams#activity", :as => "activity_stream"
  get "stream" => "diaspora_owncloud_streams#multi", :as => "stream"
  get "public" => "diaspora_owncloud_streams#public", :as => "public_stream"
  get "followed_tags" => "diaspora_owncloud_streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "diaspora_owncloud_streams#mentioned", :as => "mentioned_stream"
  get "liked" => "diaspora_owncloud_streams#liked", :as => "liked_stream"
  get "commented" => "diaspora_owncloud_streams#commented", :as => "commented_stream"
  get "aspects" => "diaspora_owncloud_streams#aspects", :as => "aspects_stream"
  
  resources :diaspora_owncloud_photos, only: %i(destroy create) do
    put :make_profile_photo
  end
  
  resources :diaspora_owncloud_notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end
  
  resource :diaspora_owncloud_user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end
  
  devise_for :users, controllers: {sessions: "diaspora_owncloud_sessions",
    :omniauth_callbacks => "omniauth_callbacks"}, 
    skip: :registration
    
  devise_scope :user do
    get "/users/sign_up" => "diaspora_owncloud_registrations#new",    :as => :new_user_registration
    post "/users"        => "diaspora_owncloud_registrations#create", :as => :user_registration
  end
  
  get 'mobile/toggle', :to => 'diaspora_owncloud_home#toggle_mobile', :as => 'toggle_mobile'
  get "/m", to: "diaspora_owncloud_home#force_mobile", as: "force_mobile"
  
  # Startpage
  root :to => 'diaspora_owncloud_home#show'
  get "podmin", to: "diaspora_owncloud_home#podmin"
  
  #diaspora_owncloud
  get "owncloud", to: "owncloud#show"
  
  get "webdav",to: "owncloud#webdav"
  
  get "webdav/file",to: "owncloud#file"
  
end

diaspora_owncloud/app/views/layouts/diaspora_owncloud/_drawer.mobile.haml
#drawer
  %header
    #global-search
      = form_tag("/search", :method => "get", :class => "search_form", "accept-charset" => "UTF-8") do
        %div
          = hidden_field_tag "utf8", "✓"
          = search_field_tag "q", nil, id: "q", placeholder: t("search"), results: "5",
                              autocomplete: "off", class: "ac_input form-control"
  %nav.navbar-inverse
    %ul
      %li= link_to t("streams.activity.title"), activity_stream_path
      %li= link_to t("streams.mentions.title"), mentioned_stream_path
      %li#all_aspects
        = link_to t("streams.aspects.title"), "#"
      %li.no-border.hide
        %ul
          - current_user.aspects.each do |aspect|
            %li= link_to aspect.name, aspects_stream_path(a_ids: [aspect.id])
      %li#followed_tags
        = link_to t("streams.followed_tag.title"), "#"
      %li.no-border.hide
        %ul
          - current_user.followed_tags.each do |tag|
            %li= tag_link(tag)
          - if current_user.followed_tags.length > 0
            %li.manage-followed-tags
              = link_to t("tag_followings.manage.title"), manage_tag_followings_path
      %li
        = link_to user_profile_path(current_user.username) do
          = t("layouts.header.profile")
          = person_image_tag(current_user, size: :thumb_small)
      %li= link_to t("_contacts"), contacts_path
      %li= link_to t("layouts.header.settings"), edit_user_path
      %li= link_to t("layouts.application.toggle"), toggle_mobile_path
      %li= link_to t("layouts.header.logout"), destroy_user_session_path, method: :delete

diaspora_owncloud/app/views/layouts/diaspora_owncloud/_footer.html.haml
%footer.footer
  .container
    .pull-left
      .powered-by-diaspora
        =t("layouts.application.powered_by")
    %ul#footer_nav.pull-right
      = render :partial =>'shared/links'

diaspora_owncloud/app/views/layouts/diaspora_owncloud/_header.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%header
  - unless current_user
    .dark-header
      %nav.navbar.navbar-inverse.navbar-fixed-top
        .container-fluid
          .row
            .col-md-12
              .navbar-header
                %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar-collapse"}}
                  %span.sr-only
                    = t("layouts.header.toggle_navigation")
                  %span.icon-bar
                  %span.icon-bar
                  %span.icon-bar
                = link_to AppConfig.settings.pod_name, root_path, class: "navbar-brand"

              .collapse.navbar-collapse#navbar-collapse
                = render "layouts/diaspora_owncloud/header_not_connected"

diaspora_owncloud/app/views/layouts/diaspora_owncloud/_header.mobile.haml
.nav.navbar-inverse.navbar-fixed-top#main-nav
  .container-fluid
    .navbar
      = link_to(image_tag("branding/logos/asterisk_white_mobile.png", class: "img-responsive"),
          stream_path, id: "header-title", class: "navbar-brand")

      - if user_signed_in?
        %ul.nav.navbar-nav#nav-badges
          -# Notifications
          %li
            = link_to diaspora_owncloud_notifications_path, class: "badge-link", id: "notification-badge" do
              %i.entypo-bell
              - if current_user.unread_notifications.size > 0
                %span.badge.badge-important#notification
                  = current_user.unread_notifications.size

          -# Conversations
          %li
            = link_to conversations_path, class: "badge-link", id: "conversations-badge" do
              %i.entypo-mail
              - if current_user.unread_message_count > 0
                %span.badge.badge-important#conversation
                  = current_user.unread_message_count

          -# Owncloud
          %li
            = link_to "", "/owncloud", :class=> 'owncloud-link', :id=> 'owncloud-link'

          -# Publisher
          %li
            = link_to "diaspora_owncloud_status_messages/new", class: "badge-link", id: "compose-badge" do
              %i.diaspora-custom-compose

          -# Menu
          %li
            %button.navbar-toggle#menu-badge{type: "button"}
              %span.sr-only
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

      - else
        = render "layouts/diaspora_owncloud/header_not_connected"

diaspora_owncloud/app/views/layouts/diaspora_owncloud/_header_not_connected.haml
%ul.nav.navbar-nav.navbar-right
  - if AppConfig.settings.enable_registrations? && !current_page?(controller: "/diaspora_owncloud_registrations", action: :new)
    %li= link_to t("devise.shared.links.sign_up"), new_user_registration_path, class: "login"
  %li= link_to t("devise.shared.links.sign_in"), new_user_session_path, class: "login"

diaspora_owncloud/app/views/layouts/diaspora_owncloud/_open_graph.haml
- if @post.present?
  %link{:rel => 'alternate', :type => "application/json+oembed", :href => "#{oembed_url(:url => post_url(@post))}"}
  = og_page_post_tags(@post)
- else
  = og_general_tags

diaspora_owncloud/app/views/layouts/diaspora_owncloud/application.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

!!!
%html{lang:  I18n.locale.to_s, dir:  (rtl?) ? 'rtl' : 'ltr'}
  %head{prefix:  og_prefix}
    %title
      = page_title yield(:page_title)

    %meta{charset:  'utf-8'}/
    %meta{"http-equiv" => "Content-Type", :content=>"text/html; charset=utf-8"}/
    %meta{name:  "description", content:  "diaspora*"}/
    %meta{name:  "author", content:  "diaspora* contributors"}/
    %meta{name:  "viewport", content:  "width=device-width, initial-scale=1"}/

    %link{rel:  'shortcut icon', href:  "#{image_path('favicon.png')}" }

    = render 'layouts/open_graph'

    = chartbeat_head_block
    = include_mixpanel

    = include_color_theme
    
    = stylesheet_link_tag :jstree_style, media:  'all'

    = stylesheet_link_tag :diaspora_owncloud, media:  'all'

    - if rtl?
      = stylesheet_link_tag :rtl, media:  'all'

    - if Rails.env.test?
      = stylesheet_link_tag :poltergeist_disable_transition, media: "all"

    = old_browser_js_support
    <!--[if IE]>
    = javascript_include_tag :ie
    <![endif]-->

    = jquery_include_tag
    = javascript_include_tag :diaspora_owncloud_main, :diaspora_owncloud_templates
    = load_javascript_locales

    = translation_missing_warnings
    = current_user_atom_tag

    = yield(:head)
    = csrf_meta_tag


    = include_gon(camel_case:  true)

  %body{ class:  "page-#{controller_name} action-#{action_name}" }
    = yield :before_content

    %noscript
      .noscript
        %h3= t("error_messages.need_javascript")

    = content_for?(:content) ? yield(:content) : yield

    = yield :after_content

    = include_chartbeat
    = include_mixpanel_guid

    .blueimp-gallery.blueimp-gallery-controls#blueimp-gallery
      .slides
      %h3.title
      %a.prev
        .entypo-chevron-small-left
      %a.next
        .entypo-chevron-small-right
      %a.close
        .entypo-cross
      %a.play-pause
      %ol.indicator

    #flash-container= flash_messages

diaspora_owncloud/app/views/layouts/diaspora_owncloud/application.mobile.haml
-# Copyright (c) 2010-2011, Diaspora Inc. This file is
-# licensed under the Affero General Public License version 3 or later. See
-# the COPYRIGHT file.

!!!
%html{:lang => I18n.locale.to_s, :dir => (rtl?) ? 'rtl' : 'ltr'}
  %head{:prefix => og_prefix}
    %title
      = pod_name

    %meta{:name => "description", :content => "diaspora* mobile"}/
    %meta{:name => "author", :content => "Diaspora, Inc."}/
    %meta{:charset => 'utf-8'}/

    / Viewport scale
    %meta{:name =>'viewport', :content => "width=device-width, minimum-scale=1 maximum-scale=1"}/
    %meta{:name => "HandheldFriendly", :content => "True"}/
    %meta{:name => "MobileOptimized", :content => "320"}/
    / Force cleartype on WP7
    %meta{'http-equiv' => "cleartype", :content => 'on'}/

    / Home screen icon (sized for retina displays)
    %link{rel: "apple-touch-icon", href: image_path("apple-touch-icon.png")}
    / For Nokia devices
    %link{rel: "shortcut icon", href: image_path("apple-touch-icon.png")}
    / For desktop
    %link{rel:  'shortcut icon', href:  image_path("favicon.png")}

    / iOS mobile web app indicator
    / NOTE(we will enable these once we don't have to rely on back/forward buttons anymore)
    /%meta{:name => "apple-mobile-web-app-capable", :content => "yes"}
    /%link{:rel => "apple-touch-startup-image", :href => "/images/apple-splash.png"}

    = render 'layouts/open_graph'

    = chartbeat_head_block

    / Stylesheets

    = include_color_theme "mobile"
    = yield(:custom_css)

    = stylesheet_link_tag :diaspora_owncloud, media:  'all'

    = stylesheet_link_tag :jstree_style, media:  'all'

    = csrf_meta_tag

    - if rtl?
      = stylesheet_link_tag :rtl, :media => 'all'

    - if Rails.env.test?
      = stylesheet_link_tag :poltergeist_disable_transition, media: "all"

    = yield(:head)

    = include_gon(:camel_case => true)
  %body
    #app
      = render "layouts/diaspora_owncloud/header"
      - if user_signed_in?
        = render "layouts/drawer"

      #main{:role => "main"}
        - if current_page?(:activity_stream)
          %h3
            = t('streams.activity.title')
        = yield

    / javascripts at the bottom
    = jquery_include_tag
    = javascript_include_tag "diaspora_owncloud_mobile/mobile"
    = load_javascript_locales
    = include_chartbeat

diaspora_owncloud/app/views/layouts/diaspora_owncloud/error_page.haml
!!!
%html
  %head
    %title= page_title yield(:page_title)

    %link{rel: "shortcut icon", href: image_path("favicon.png")}
    %link{rel: "apple-touch-icon", href: image_path("apple-touch-icon.png")}

    = stylesheet_link_tag :error_pages, media: "all"

    = yield(:head)

  %body{class: "error-#{@code}", id: "error_#{@code}"}
    = yield

diaspora_owncloud/app/views/layouts/diaspora_owncloud/notifier.html.erb
<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:14px;color:#333;">
  <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:14px;color:#333;">
    <tr width="100%">
      <% if @sender %>
        <td style="vertical-align:top;" width="80px">
          <div style="background-color:#eee;height:70px;width:70px;">
            <img alt="<%=@sender.name%>" src="<%=@sender.profile.image_url(:medium)%>" style="border:0;display:block;display:relative;top:0;left:0;" height="70px" width="70px">
          </div>
        </td>
      <% end %>
      <td style="vertical-align:top;">
        <%= yield %>
      </td>
    </tr>
  </table>

  <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;color:#999; padding-top:10px; margin-top:10px; border-top: 1px solid #ddd;">
    <tr>
      <td>
        <%= t('notifier.email_sent_by_diaspora', :pod_name => pod_name) %>
        <a href="<%=edit_user_url%>">
          <%= t('notifier.click_here') %>
        </a>
        <%=t('notifier.to_change_your_notification_settings')%>.
      </td>
    </tr>
  </table>
  <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:14px;color:#333;">
    <tr>
      <td style="text-align:center;padding:30px;">
        <img src="<%= image_url("branding/logos/logo_small.png") %>" alt="diaspora*" width="59px" height="14px"/>
      </td>
    </tr>
  </table>
</table>

diaspora_owncloud/app/views/layouts/diaspora_owncloud/notifier.text.haml
!= yield
!= t('notifier.email_sent_by_diaspora', :pod_name => pod_name) 
!= t('notifier.to_change_your_notification_settings')
!= edit_user_url

diaspora_owncloud/app/views/layouts/diaspora_owncloud/with_header.html.haml
- content_for :before_content do
    = render 'layouts/diaspora_owncloud/header'

= render template: "layouts/diaspora_owncloud/application"

diaspora_owncloud/app/views/layouts/diaspora_owncloud/with_header_with_footer.html.haml
- content_for :after_content do
    = render 'layouts/diaspora_owncloud/footer'

= render template: "layouts/diaspora_owncloud/with_header"