config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'
require "sidekiq/cron/web"

Diaspora::Application.routes.draw do
  
  resources :report, except: %i(edit new show)

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  # Federation
  mount DiasporaFederation::Engine => "/"

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares, only: %i(create)

  resources :status_messages, :only => [:new, :create]
  
  resources :posts, only: %i(show destroy) do
    member do
      get :interactions
    end

    resource :participation, only: %i(create destroy)
    resources :poll_participations, only: :create
    resources :likes, only: %i(create destroy index)
    resources :comments, only: %i(new create destroy index)
  end

  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
#  get "activity" => "streams#activity", :as => "activity_stream"
#  get "stream" => "streams#multi", :as => "stream"
#  get "public" => "streams#public", :as => "public_stream"
#  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
#  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
#  get "liked" => "streams#liked", :as => "liked_stream"
#  get "commented" => "streams#commented", :as => "commented_stream"
#  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects, except: %i(index new edit) do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end
  
  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations, except: %i(edit update destroy)  do
    resources :messages, only: %i(create)
    delete 'visibility' => 'conversation_visibilities#destroy'
  end
  
  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end

  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  # Users and people

  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end
  
  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end

  controller :users do
    get "public/:username"          => :public,                  :as => :users_public
    get "getting_started"           => :getting_started,         :as => :getting_started
    get "confirm_email/:token"      => :confirm_email,           :as => :confirm_email
    get "privacy"                   => :privacy_settings,        :as => :privacy_settings
    put "privacy"                   => :update_privacy_settings, :as => :update_privacy_settings
    get "getting_started_completed" => :getting_started_completed
  end

#  devise_for :users, controllers: {sessions: "sessions",
#    :omniauth_callbacks => "omniauth_callbacks"}, 
#    skip: :registration
#    
#  devise_scope :user do
#    get "/users/sign_up" => "registrations#new",    :as => :new_user_registration
#    post "/users"        => "registrations#create", :as => :user_registration
#  end

  get "users/invitations"  => "invitations#new",    :as => "new_user_invitation"
  post "users/invitations" => "invitations#create", :as => "user_invitation"

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope "admins", controller: :admins do
    match :user_search, via: [:get, :post]
    get :admin_inviter
    get :weekly_user_stats
    get :stats, as: "pod_stats"
    get :dashboard, as: "admin_dashboard"
    get "add_invites/:invite_code_id" => "admins#add_invites", :as => "add_invites"
  end

  namespace :admin do
    resources :pods, only: :index do
      post :recheck
    end

    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts, only: %i(index)
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, only: %i(show index) do
    resources :status_messages, only: %i(new create)
    resources :photos, except:  %i(new update)
    get :contacts
    get :stream
    get :hovercard

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }
  get '/u/:username/profile_photo' => 'users#user_photo', :constraints => { :username => /[^\/]+/ }

  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

#  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'
#  get "/m", to: "home#force_mobile", as: "force_mobile"

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  # NodeInfo
  get ".well-known/nodeinfo", to: "node_info#jrd"
  get "nodeinfo/:version",    to: "node_info#document", as: "node_info", constraints: {version: /\d+\.\d+/}
  get "statistics",           to: "node_info#statistics"
  get "statistics",           to: "node_info#statistics"

  # Terms
  if AppConfig.settings.terms.enable? || Rails.env.test?
    get 'terms' => 'terms#index'
  end

  # Relay
  get ".well-known/x-social-relay" => "social_relay#well_known"

  # Startpage
#  root :to => 'home#show'
#  get "podmin", to: "home#podmin"

  namespace :api do
    namespace :openid_connect do
      resources :clients, only: :create
      get "clients/find", to: "clients#find"

      post "access_tokens", to: "token_endpoint#create"

      # Authorization Servers MUST support the use of the HTTP GET and POST methods at the Authorization Endpoint
      # See http://openid.net/specs/openid-connect-core-1_0.html#AuthResponseValidation
      resources :authorizations, only: %i(new create destroy)
      post "authorizations/new", to: "authorizations#new"
      get "user_applications", to: "user_applications#index"
      get "jwks.json", to: "id_tokens#jwks"
      match "user_info", to: "user_info#show", via: %i(get post)
    end
  end

  get ".well-known/webfinger", to: "api/openid_connect/discovery#webfinger"
  get ".well-known/openid-configuration", to: "api/openid_connect/discovery#configuration"
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  include Diaspora::Federated::Base
  include Diaspora::Fields::Guid
  include Diaspora::Fields::Author

  has_many :conversation_visibilities, dependent: :destroy
  has_many :participants, class_name: "Person", through: :conversation_visibilities, source: :person
  has_many :messages, -> { order("created_at ASC") }, inverse_of: :conversation

  validate :max_participants
  validate :local_recipients

  def max_participants
    errors.add(:max_participants, "too many participants") if participants.count > 20
  end

  def local_recipients
    recipients.each do |recipient|
      if recipient.local?
        unless recipient.owner.contacts.where(person_id: author.id).any? ||
            (author.owner && author.owner.podmin_account?)
          errors.add(:all_recipients, "recipient not allowed")
        end
      end
    end
  end

  accepts_nested_attributes_for :messages

  def recipients
    self.participants - [self.author]
  end

  def first_unread_message(user)
    if visibility = self.conversation_visibilities.where(:person_id => user.person.id).where('unread > 0').first
      self.messages.to_a[-visibility.unread]
    end
  end

  def set_read(user)
    if visibility = self.conversation_visibilities.where(:person_id => user.person.id).first
      visibility.unread = 0
      visibility.save
    end
  end

  def participant_handles
    participants.map(&:diaspora_handle).join(";")
  end

  def participant_handles=(handles)
    handles.split(";").each do |handle|
      participants << Person.find_or_fetch_by_identifier(handle)
    end
  end

  def last_author
    return unless @last_author.present? || messages.size > 0
    @last_author_id ||= messages.pluck(:author_id).last
    @last_author ||= Person.includes(:profile).where(id: @last_author_id).first
  end

  def ordered_participants
    @ordered_participants ||= (messages.map(&:author).reverse + participants).uniq
  end

  def subject
    self[:subject].blank? ? I18n.t("conversations.new.subject_default") : self[:subject]
  end

  def subscribers
    recipients
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :mobile, :json, :js

  def index
    @visibilities = ConversationVisibility.includes(:conversation)
                                          .order("conversations.updated_at DESC")
                                          .where(person_id: current_user.person_id)
                                          .paginate(page: params[:page], per_page: 15)

    if params[:conversation_id]
      @conversation = Conversation.joins(:conversation_visibilities)
                                  .where(conversation_visibilities: {
                                           person_id:       current_user.person_id,
                                           conversation_id: params[:conversation_id]
                                         }).first

      if @conversation
        @first_unread_message_id = @conversation.first_unread_message(current_user).try(:id)
        @conversation.set_read(current_user)
      end
    end

    gon.contacts = contacts_data

    respond_with do |format|
      format.html
      format.json { render json: @visibilities.map(&:conversation), status: 200 }
    end
  end

  def create
    contact_ids = params[:contact_ids]

    # Can't split nil
    if contact_ids
      contact_ids = contact_ids.split(',') if contact_ids.is_a? String
      person_ids = current_user.contacts.where(id: contact_ids).pluck(:person_id)
    end

    opts = params.require(:conversation).permit(:subject)
    opts[:participant_ids] = person_ids
    opts[:message] = { text: params[:conversation][:text] }
    @conversation = current_user.build_conversation(opts)

    @response = {}
    if person_ids.present? && @conversation.save
      Diaspora::Federation::Dispatcher.defer_dispatch(current_user, @conversation)
      @response[:success] = true
      @response[:message] = I18n.t('conversations.create.sent')
      @response[:conversation_id] = @conversation.id
    else
      @response[:success] = false
      @response[:message] = I18n.t('conversations.create.fail')
      if person_ids.blank?
        @response[:message] = I18n.t('conversations.create.no_contact')
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    respond_to do |format|
      format.html do
        redirect_to conversations_path(:conversation_id => params[:id])
        return
      end

      if @conversation = current_user.conversations.where(id: params[:id]).first
        @first_unread_message_id = @conversation.first_unread_message(current_user).try(:id)
        @conversation.set_read(current_user)

        format.js
        format.json { render :json => @conversation, :status => 200 }
      else
        redirect_to conversations_path
      end
    end
  end

  def new
    if !params[:modal] && !session[:mobile_view] && request.format.html?
      redirect_to conversations_path
      return
    end

    @contacts_json = contacts_data.to_json
    @contact_ids = ""

    if params[:contact_id]
      @contact_ids = current_user.contacts.find(params[:contact_id]).id
    elsif params[:aspect_id]
      @contact_ids = current_user.aspects.find(params[:aspect_id]).contacts.map{|c| c.id}.join(',')
    end
    if session[:mobile_view] == true && request.format.html?
      render :layout => true
    else
      render :layout => false
    end
  end

  private

  def contacts_data
    current_user.contacts.sharing.joins(person: :profile)
      .pluck(*%w(contacts.id profiles.first_name profiles.last_name people.diaspora_handle))
      .map {|contact_id, *name_attrs|
        {value: contact_id, name: ERB::Util.h(Person.name_from_attrs(*name_attrs)) }
      }
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def conversation_class(conversation, unread_count, selected_conversation_id)
    conv_class = unread_count > 0 ? "unread " : ""
    if selected_conversation_id && conversation.id == selected_conversation_id
      conv_class << "selected"
    end
    conv_class
  end
end

app/views/conversations/_conversation.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- conversation = visibility.conversation
.conversation-wrapper{ :"data-conversation-path" => conversation_path(conversation) }
  .stream_element.conversation{data:  {guid: conversation.id},
                               class: conversation_class(conversation, visibility.unread, @conversation.try(:id))}
    .media
      .img
        - other_participants = conversation.ordered_participants - [current_user.person]
        - if other_participants.first.present?
          = person_image_tag(other_participants.first)
          - if other_participants.count > 1
            .participants_count
              = other_participants.count - 1

      .bg
        .badge.badge-default.message-count.pull-right
          = conversation.messages.size
        - if visibility.unread > 0
          .badge.badge-important.unread-message-count.pull-right
            = visibility.unread
        .subject
          %div{ :class => direction_for(conversation.subject) }
            = conversation.subject
        .timestamp
          = timeago(conversation.updated_at)
        .last_author
          - if conversation.last_author.present?
            = conversation.last_author.name
        .last_message
          - if conversation.messages.present?
            %em
              = conversation.messages.last.message.plain_text_without_markdown
        - if other_participants.count > 1
          .participants
            - other_participants.drop(1).take(15).each do |participant|
              = person_image_tag(participant)

app/views/conversations/_conversation.mobile.haml
- conversation = visibility.conversation
%a.conversation{ :href => conversation_path(conversation) }
  .stream_element.conversation{data: {guid: conversation.id}, class: ("unread" if visibility.unread > 0)}
    .media
      .img
        = person_image_tag(conversation.author, size: :thumb_small)

      .bg
        = render partial: "conversation_subject",
                 locals:  { conversation: conversation, unread_count: visibility.unread }

        .last_author
          .timestamp
            = timeago(conversation.updated_at)

          - if conversation.last_author.present?
            = conversation.last_author.name

          - if conversation.participants.size > 2
            %span.participant_count
              = "(+#{conversation.participants.size - 1})"

app/views/conversations/_conversation_subject.haml
.subject
  .badge.badge-default.message-count.pull-right
    = conversation.messages.size
  - if unread_count > 0
    .badge.badge-important.unread-message-count.pull-right
      = unread_count

  %div{ :class => direction_for(conversation.subject) }
    = conversation.subject[0..30]

app/views/conversations/_message.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.stream_element.message{data: {guid: message.id}, id: ("first_unread" if @first_unread_message_id == message.id)}
  .media
    .media-left
      = person_image_link(message.author, size: :thumb_small, class: "media-object")
    .media-body
      = person_link(message.author, :class => 'author from')
      = timeago(message.created_at)

      %div{ :class => direction_for(message.text) }
        .message-content
          = message.message.markdownified

app/views/conversations/_messages.haml
.stream
  = render partial: "message", collection: conversation.messages

  .stream_element.new-message
    .media
      .media-left
        = owner_image_tag(:thumb_small)
      .media-body
        = form_for [conversation, Message.new], html: {class: "control-group"} do |message|
          .form-group
            %label#messageLabel.sr-only{for: "message_text"}
              = t("conversations.new.message")
            = message.text_area :text,
                                rows:     5,
                                tabindex: 1,
                                class:    "form-control form-group",
                                aria:     {labelledby: "messageLabel"}

          = message.submit t("conversations.show.reply"),
                            "data-disable-with" => t("conversations.show.replying"),
                            class: "btn btn-primary pull-right", tabindex: 2
          .clearfix

app/views/conversations/_new.haml
.container-fluid
  = form_for Conversation.new, html: {class: "form-horizontal form_do_not_clear"}, remote: true do |conversation|
    .form-group
      %label#toLabel{for: "contact_ids"}
        = t(".to")
      = text_field_tag "contact_autocomplete", nil, class: "form-control"
    .form-group
      %label#subjectLabel{for: "conversation_subject"}
        = t(".subject")
      = conversation.text_field :subject,
                                class: "input-block-level form-control",
                                aria:  {labelledby: "subjectLabel"}
    .form-group
      %label#messageLabel.sr-only{for: "conversation_text"}
        = t(".message")
      = text_area_tag "conversation[text]",
                      "",
                      rows:  5,
                      class: "input-block-level form-control",
                      aria:  {labelledby: "messageLabel"}
    .form-group
      = conversation.submit t('.send'), 'data-disable-with' => t('.sending'), class: 'btn btn-primary pull-right'

app/views/conversations/_show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.conversation-participants.framed-content.clearfix
  .control-icons.pull-right
    - if conversation.participants.count > 1
      = link_to content_tag(:i, nil, class: "entypo-cross"),
                conversation_visibility_path(conversation),
                method: "delete",
                data:   {confirm: "#{t('.hide')}?"},
                title:  t(".hide"),
                class:  "hide_conversation"
    - else
      = link_to content_tag(:i, nil, class: "entypo-trash"),
                conversation_visibility_path(conversation),
                method: "delete",
                data:   {confirm: "#{t('.delete')}?"},
                title:  t(".delete"),
                class:  "delete_conversation"

  %h3{ :class => direction_for(conversation.subject) }
    = conversation.subject

  - for participant in conversation.participants
    = person_image_link(participant, :size => :thumb_small)

.stream
  = render partial: 'messages', locals: { conversation: conversation }

app/views/conversations/_show.mobile.haml
-# Copyright (c) 2010-2011, Diaspora Inc. This file is
-# licensed under the Affero General Public License version 3 or later. See
-# the COPYRIGHT file.

.conversation
  .conversation-participants.header-full-width
    .delete_conversation.pull-right
      = link_to(raw("<i class='entypo-trash'></i>"), conversation_visibility_path(conversation),
              method: 'delete', data: { confirm: "#{t('.delete')}?" }, class: "remove")

    %h3
      = conversation.subject
    .last-message-timeago
      != t('.last_message', timeago: timeago(conversation.updated_at))

    .avatars
      - for participant in conversation.participants
        .avatar
          = person_image_link(participant, size: :thumb_small)
    .clear

  = render partial: 'messages', locals: { conversation: conversation }

app/views/conversations/create.js.erb
var response = <%= raw @response.to_json %>;
<% if session[:mobile_view] %>
  window.location.href = "<%= conversations_path(conversation_id: @conversation.id) %>";
<% else %>
  if(response.success){
    app.flashMessages.success(response.message);
    $("#new_conversation").removeClass('form_do_not_clear').clearForm();
    window.location.href = "<%= conversations_path(conversation_id: @conversation.id) %>";
  } else {
    app.flashMessages.error(response.message);
  }
<% end %>

app/views/conversations/index.mobile.haml
-#   Copyright (c) 2010-2012, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.clearfix.conversations-title
  %h3= t(".inbox")
  = link_to t(".new_conversation"), new_conversation_path, class: "btn btn-default pull-right"

- flash.each do |name, msg|
  %div{ id: "flash_#{name}",  class: "expose" }
    .message= msg
  .stream
    %p{ class: "conversation_#{name}" }= msg

#conversation_inbox
  .stream.conversations
    - if @visibilities.count > 0
      = render partial: "conversations/conversation", collection: @visibilities, as: :visibility
    - else
      .no-messages
        %i
          = t(".no_messages")

  = will_paginate @visibilities, previous_label: "&laquo;", next_label: "&raquo;", inner_window: 1, outer_window: 0,
      renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/conversations/new.html.haml
:javascript
  $(document).ready(function () {
    var data = $.parseJSON( "#{escape_javascript(@contacts_json)}" );
    new app.views.ConversationsForm({
      contacts: data,
      prefillName: "#{h params[:name]}",
      prefillValue: "#{@contact_ids}"
    });
  });

= render 'conversations/new'

app/views/conversations/new.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= javascript_include_tag :jquery

:javascript
  $(document).ready(function () {
    var data = $.parseJSON( "#{escape_javascript(@contacts_json)}" ),
        autocompleteInput = $("#contact_autocomplete");

    autocompleteInput.autoSuggest(data, {
      selectedItemProp: "name",
      searchObjProps: "name",
      asHtmlID: "contact_ids",
      retrieveLimit: 10,
      minChars: 1,
      keyDelay: 0,
      startText: '',
      emptyText: "#{t('no_results')}",
      preFill: [{name : "#{h params[:name]}",
                 value : "#{@contact_ids}"}]
      });
    autocompleteInput.focus();
  });

.col-md-6#new_conversation_pane
  .container-fluid.row
    %h3
      = t('conversations.index.new_conversation')

  = render 'conversations/new'

app/views/conversations/show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= render 'show', :conversation => @conversation

app/views/conversations/show.js.erb
if($('.stream_container').hasClass('hidden')){
  $('#conversation_new').hide();
  $('.stream_container').removeClass('hidden');
}

$('#conversation_show').html("<%= escape_javascript(render('conversations/show', :conversation => @conversation)) %>");

$(".stream_element", "#conversation_inbox").removeClass('selected');
$(".stream_element[data-guid='<%= @conversation.id %>']", "#conversation_inbox").addClass('selected');
$('#conversation_show').trigger("conversation:loaded");